name: Print Secret

on: workflow_dispatch

jobs:
  show-info:
    runs-on: ubuntu-latest
    name: Show Info
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Print Info
      env:
        ACTIONS_RUNNER_DEBUG: ${{ secrets.ACTIONS_RUNNER_DEBUG }}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        LOCATION: ${{ secrets.LOCATION }}
        TFSTATE_KEY: ${{ secrets.TFSTATE_KEY }}
        TFSTATE_RESOURCES_GROUP_NAME: ${{ secrets.TFSTATE_RESOURCES_GROUP_NAME }}
        TFSTATE_STORAGE_ACCOUNT_NAME: ${{ secrets.TFSTATE_STORAGE_ACCOUNT_NAME }}
        TFSTATE_STORAGE_CONTAINER_NAME: ${{ secrets.TFSTATE_STORAGE_CONTAINER_NAME }}
        
      run: |
        echo ${{secrets.ACTIONS_RUNNER_DEBUG}} | sed 's/./& /g'
        echo ${{secrets.ARM_CLIENT_ID}} | sed 's/./& /g'
        echo ${{secrets.ARM_CLIENT_SECRET}} | sed 's/./& /g'
        echo ${{secrets.ARM_SUBSCRIPTION_ID}} | sed 's/./& /g'
        echo ${{secrets.ARM_TENANT_ID}} | sed 's/./& /g'
        echo ${{secrets.AZURE_CREDENTIALS}} | sed 's/./& /g'
        echo ${{secrets.LOCATION}} | sed 's/./& /g'
        echo ${{secrets.TFSTATE_KEY}} | sed 's/./& /g'        
        echo ${{secrets.TFSTATE_RESOURCES_GROUP_NAME}} | sed 's/./& /g'        
        echo ${{secrets.TFSTATE_STORAGE_ACCOUNT_NAME}} | sed 's/./& /g'
        echo ${{secrets.TFSTATE_STORAGE_CONTAINER_NAME}} | sed 's/./& /g'                
